version: "3"

services:
  web:
    image: php:7.4-apache
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpapp.rule=Host(`yourdomain.com`)" # Replace with your domain
      - "traefik.http.services.phpapp.loadbalancer.server.port=80"
    volumes:
      - ./src:/var/www/html
    networks:
      - web

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=your_database
      - MYSQL_USER=your_username
      - MYSQL_PASSWORD=your_password
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - web

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.yourdomain.com`)" # Replace with your domain
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
    environment:
      - PMA_HOST=db
      - PMA_USER=your_username
      - PMA_PASSWORD=your_password
    depends_on:
      - db
    networks:
      - web

networks:
  web:
    external: true
